kind: Service
apiVersion: v1
metadata:
  name: scheduler-service
spec:
  selector:
    app: scheduler-service
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30082
  type: NodePort
---
apiVerson: apps/v1
kind: Deployment
metadata:
  name: scheduler-service
spec:
  selector:
    matchLabels:
      app: scheduler-service
    replicas: 1
    template:
      metadata:
        labels:
          app: scheduler-service
        spec:
          containers:
            - name: scheduler-service
              image: gowthamra09/scheduler-service
              imagePullPolicy: Always
              ports:
                - containerPort: 8080
