apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-registration-deployment
  labels:
    app: flask-dock 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-dock 
  template:
    metadata:
      labels:
        app: flask-dock 
    spec:
      containers:
      - name: flask-dock
        image: chelccelia/flask-dock:order-food
        imagePullPolicy: Always 
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: n-regcred

---

apiVersion: v1
kind: Service
metadata:
  name: user-registration-service
  labels:
    app: user-registration-service
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30001
  selector:
    app: flask-dock