apiVersion: v1
kind: Service
metadata:
  name: user-registration-service
  labels:
    app: user-registration-service
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30001
  selector:
    app: flask-dock