apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-ui-deployment
  labels:
    app: workflow-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workflow-ui
  template:
    metadata:
      labels:
        app: workflow-ui
    spec:
      containers:
      - name: workflow-ui
        image: nevin160/workflow-ui
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: n-regcred

---

apiVersion: v1
kind: Service
metadata:
  name: workflow-ui-service
  labels:
    app: workflow-ui-service
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30000
  selector:
    app: workflow-ui
